# Site variables
title: Webstoemp
email: hello@webstoemp.com
baseurl: ""
url: "http://www.webstoemp.com"
twitter_username: jeromecoupe
github_username:  jeromecoupe
html_description: "The blog and portfolio of Jérôme Coupé, a web designer from Brussels, Belgium"

# Build settings
highlighter: rouge
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

permalink: /blog/:title/

collections:
  projects:
    output: true
    permalink: /work/:title/

# Defaults front matter variables for various types
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
      current_nav: "blog"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "portfolio"
      current_nav: "work"

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - scss
  - js/modules

include:
  - _pages
